default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: equitabletod_development


test:
  <<: *default
  database: equitabletod_test

production:
  schema_search_path: <%= schema = ENV.fetch('DB_SCHEMA_SEARCH_PATH') { 'tstation' } + ',public' %>
